export const getAudioFile = (expressionKey: string) => {
  switch (expressionKey) {
    // greetings
    case 'greetings_001':
      return require('audio/greetings_001.mp3');
    case 'greetings_002':
      return require('audio/greetings_002.mp3');
    case 'greetings_003':
      return require('audio/greetings_003.mp3');
    case 'greetings_004':
      return require('audio/greetings_004.mp3');
    case 'greetings_005':
      return require('audio/greetings_005.mp3');
    case 'greetings_006':
      return require('audio/greetings_006.mp3');
    case 'greetings_007':
      return require('audio/greetings_007.mp3');
    case 'greetings_008':
      return require('audio/greetings_008.mp3');
    case 'greetings_009':
      return require('audio/greetings_009.mp3');
    case 'greetings_010':
      return require('audio/greetings_010.mp3');
    case 'greetings_011':
      return require('audio/greetings_011.mp3');
    case 'greetings_012':
      return require('audio/greetings_012.mp3');
    case 'greetings_013':
      return require('audio/greetings_013.mp3');
    case 'greetings_014':
      return require('audio/greetings_014.mp3');
    case 'greetings_015':
      return require('audio/greetings_015.mp3');
    case 'greetings_016':
      return require('audio/greetings_016.mp3');
    case 'greetings_017':
      return require('audio/greetings_017.mp3');
    case 'greetings_018':
      return require('audio/greetings_018.mp3');
    case 'greetings_019':
      return require('audio/greetings_019.mp3');
    case 'greetings_020':
      return require('audio/greetings_020.mp3');
    case 'greetings_021':
      return require('audio/greetings_021.mp3');
    case 'greetings_022':
      return require('audio/greetings_022.mp3');
    case 'greetings_023':
      return require('audio/greetings_023.mp3');
    case 'greetings_024':
      return require('audio/greetings_024.mp3');
    case 'greetings_025':
      return require('audio/greetings_025.mp3');
    case 'greetings_026':
      return require('audio/greetings_026.mp3');
    case 'greetings_027':
      return require('audio/greetings_027.mp3');
    case 'greetings_028':
      return require('audio/greetings_028.mp3');
    case 'greetings_029':
      return require('audio/greetings_029.mp3');
    case 'greetings_030':
      return require('audio/greetings_030.mp3');
    case 'greetings_031':
      return require('audio/greetings_031.mp3');
    case 'greetings_032':
      return require('audio/greetings_032.mp3');
    case 'greetings_033':
      return require('audio/greetings_033.mp3');
    case 'greetings_034':
      return require('audio/greetings_034.mp3');
    case 'greetings_035':
      return require('audio/greetings_035.mp3');
    case 'greetings_036':
      return require('audio/greetings_036.mp3');
    case 'greetings_037':
      return require('audio/greetings_037.mp3');
    case 'greetings_038':
      return require('audio/greetings_038.mp3');
    case 'greetings_039':
      return require('audio/greetings_039.mp3');
    case 'greetings_040':
      return require('audio/greetings_040.mp3');
    case 'greetings_041':
      return require('audio/greetings_041.mp3');
    case 'greetings_042':
      return require('audio/greetings_042.mp3');
    case 'greetings_043':
      return require('audio/greetings_043.mp3');
    case 'greetings_044':
      return require('audio/greetings_044.mp3');
    case 'greetings_045':
      return require('audio/greetings_045.mp3');
    case 'greetings_046':
      return require('audio/greetings_046.mp3');

    // education
    case 'education_001':
      return require('audio/education_001.mp3');
    case 'education_002':
      return require('audio/education_002.mp3');
    case 'education_003':
      return require('audio/education_003.mp3');
    case 'education_004':
      return require('audio/education_004.mp3');
    case 'education_005':
      return require('audio/education_005.mp3');
    case 'education_006':
      return require('audio/education_006.mp3');
    case 'education_007':
      return require('audio/education_007.mp3');
    case 'education_008':
      return require('audio/education_008.mp3');
    case 'education_009':
      return require('audio/education_009.mp3');
    case 'education_010':
      return require('audio/education_010.mp3');
    case 'education_011':
      return require('audio/education_011.mp3');
    case 'education_012':
      return require('audio/education_012.mp3');
    case 'education_013':
      return require('audio/education_013.mp3');
    case 'education_014':
      return require('audio/education_014.mp3');
    case 'education_015':
      return require('audio/education_015.mp3');
    case 'education_016':
      return require('audio/education_016.mp3');
    case 'education_017':
      return require('audio/education_017.mp3');
    case 'education_018':
      return require('audio/education_018.mp3');
    case 'education_019':
      return require('audio/education_019.mp3');
    case 'education_020':
      return require('audio/education_020.mp3');
    case 'education_021':
      return require('audio/education_021.mp3');
    case 'education_022':
      return require('audio/education_022.mp3');

    // Add more education cases up to 'education_022'

    // fashion
    case 'fashion_001':
      return require('audio/fashion_001.mp3');
    case 'fashion_002':
      return require('audio/fashion_002.mp3');
    case 'fashion_003':
      return require('audio/fashion_003.mp3');
    case 'fashion_004':
      return require('audio/fashion_004.mp3');
    case 'fashion_005':
      return require('audio/fashion_005.mp3');
    case 'fashion_006':
      return require('audio/fashion_006.mp3');
    case 'fashion_007':
      return require('audio/fashion_007.mp3');
    case 'fashion_008':
      return require('audio/fashion_008.mp3');
    case 'fashion_009':
      return require('audio/fashion_009.mp3');
    case 'fashion_010':
      return require('audio/fashion_010.mp3');
    case 'fashion_011':
      return require('audio/fashion_011.mp3');
    case 'fashion_012':
      return require('audio/fashion_012.mp3');
    case 'fashion_013':
      return require('audio/fashion_013.mp3');
    case 'fashion_014':
      return require('audio/fashion_014.mp3');
    case 'fashion_015':
      return require('audio/fashion_015.mp3');
    case 'fashion_016':
      return require('audio/fashion_016.mp3');
    case 'fashion_017':
      return require('audio/fashion_017.mp3');
    case 'fashion_018':
      return require('audio/fashion_018.mp3');
    case 'fashion_019':
      return require('audio/fashion_019.mp3');
    case 'fashion_020':
      return require('audio/fashion_020.mp3');
    case 'fashion_021':
      return require('audio/fashion_021.mp3');
    case 'fashion_022':
      return require('audio/fashion_022.mp3');
    case 'fashion_023':
      return require('audio/fashion_023.mp3');
    case 'fashion_024':
      return require('audio/fashion_024.mp3');
    case 'fashion_025':
      return require('audio/fashion_025.mp3');
    case 'fashion_026':
      return require('audio/fashion_026.mp3');
    case 'fashion_027':
      return require('audio/fashion_027.mp3');
    case 'fashion_028':
      return require('audio/fashion_028.mp3');
    case 'fashion_029':
      return require('audio/fashion_029.mp3');
    case 'fashion_030':
      return require('audio/fashion_030.mp3');
    case 'fashion_031':
      return require('audio/fashion_031.mp3');
    case 'fashion_032':
      return require('audio/fashion_032.mp3');
    case 'fashion_033':
      return require('audio/fashion_033.mp3');
    case 'fashion_034':
      return require('audio/fashion_034.mp3');
    case 'fashion_035':
      return require('audio/fashion_035.mp3');
    case 'fashion_036':
      return require('audio/fashion_036.mp3');

    // health
    case 'health_001':
      return require('audio/health_001.mp3');
    case 'health_002':
      return require('audio/health_002.mp3');
    case 'health_003':
      return require('audio/health_003.mp3');
    case 'health_004':
      return require('audio/health_004.mp3');
    case 'health_005':
      return require('audio/health_005.mp3');
    case 'health_006':
      return require('audio/health_006.mp3');
    case 'health_007':
      return require('audio/health_007.mp3');
    case 'health_008':
      return require('audio/health_008.mp3');
    case 'health_009':
      return require('audio/health_009.mp3');
    case 'health_010':
      return require('audio/health_010.mp3');
    case 'health_011':
      return require('audio/health_011.mp3');
    case 'health_012':
      return require('audio/health_012.mp3');
    case 'health_013':
      return require('audio/health_013.mp3');
    case 'health_014':
      return require('audio/health_014.mp3');
    case 'health_015':
      return require('audio/health_015.mp3');
    case 'health_016':
      return require('audio/health_016.mp3');
    case 'health_017':
      return require('audio/health_017.mp3');
    case 'health_018':
      return require('audio/health_018.mp3');
    case 'health_019':
      return require('audio/health_019.mp3');
    case 'health_020':
      return require('audio/health_020.mp3');
    case 'health_021':
      return require('audio/health_021.mp3');
    case 'health_022':
      return require('audio/health_022.mp3');

    // healthcare
    case 'healthcare_001':
      return require('audio/healthcare_001.mp3');
    case 'healthcare_002':
      return require('audio/healthcare_002.mp3');
    case 'healthcare_003':
      return require('audio/healthcare_003.mp3');
    case 'healthcare_004':
      return require('audio/healthcare_004.mp3');
    case 'healthcare_005':
      return require('audio/healthcare_005.mp3');
    case 'healthcare_006':
      return require('audio/healthcare_006.mp3');
    case 'healthcare_007':
      return require('audio/healthcare_007.mp3');
    case 'healthcare_008':
      return require('audio/healthcare_008.mp3');
    case 'healthcare_009':
      return require('audio/healthcare_009.mp3');
    case 'healthcare_010':
      return require('audio/healthcare_010.mp3');
    case 'healthcare_011':
      return require('audio/healthcare_011.mp3');
    case 'healthcare_012':
      return require('audio/healthcare_012.mp3');
    case 'healthcare_013':
      return require('audio/healthcare_013.mp3');
    case 'healthcare_014':
      return require('audio/healthcare_014.mp3');
    case 'healthcare_015':
      return require('audio/healthcare_015.mp3');
    case 'healthcare_016':
      return require('audio/healthcare_016.mp3');
    case 'healthcare_017':
      return require('audio/healthcare_017.mp3');
    case 'healthcare_018':
      return require('audio/healthcare_018.mp3');
    case 'healthcare_019':
      return require('audio/healthcare_019.mp3');
    case 'healthcare_020':
      return require('audio/healthcare_020.mp3');
    case 'healthcare_021':
      return require('audio/healthcare_021.mp3');
    case 'healthcare_022':
      return require('audio/healthcare_022.mp3');
    case 'healthcare_023':
      return require('audio/healthcare_023.mp3');
    case 'healthcare_024':
      return require('audio/healthcare_024.mp3');
    case 'healthcare_025':
      return require('audio/healthcare_025.mp3');
    case 'healthcare_026':
      return require('audio/healthcare_026.mp3');
    case 'healthcare_027':
      return require('audio/healthcare_027.mp3');
    case 'healthcare_028':
      return require('audio/healthcare_028.mp3');
    case 'healthcare_029':
      return require('audio/healthcare_029.mp3');
    case 'healthcare_030':
      return require('audio/healthcare_030.mp3');
    case 'healthcare_031':
      return require('audio/healthcare_031.mp3');
    case 'healthcare_032':
      return require('audio/healthcare_032.mp3');
    case 'healthcare_033':
      return require('audio/healthcare_033.mp3');
    case 'healthcare_034':
      return require('audio/healthcare_034.mp3');
    case 'healthcare_035':
      return require('audio/healthcare_035.mp3');
    case 'healthcare_036':
      return require('audio/healthcare_036.mp3');
    case 'healthcare_037':
      return require('audio/healthcare_037.mp3');
    case 'healthcare_038':
      return require('audio/healthcare_038.mp3');
    case 'healthcare_039':
      return require('audio/healthcare_039.mp3');
    case 'healthcare_040':
      return require('audio/healthcare_040.mp3');
    case 'humans_001':
      return require('audio/humans_001.mp3');
    case 'humans_002':
      return require('audio/humans_002.mp3');
    case 'humans_003':
      return require('audio/humans_003.mp3');
    case 'humans_004':
      return require('audio/humans_004.mp3');
    case 'humans_005':
      return require('audio/humans_005.mp3');
    case 'humans_006':
      return require('audio/humans_006.mp3');
    case 'humans_007':
      return require('audio/humans_007.mp3');
    case 'humans_008':
      return require('audio/humans_008.mp3');
    case 'humans_009':
      return require('audio/humans_009.mp3');
    case 'humans_010':
      return require('audio/humans_010.mp3');
    case 'humans_011':
      return require('audio/humans_011.mp3');
    case 'humans_012':
      return require('audio/humans_012.mp3');
    case 'humans_013':
      return require('audio/humans_013.mp3');
    case 'humans_014':
      return require('audio/humans_014.mp3');
    case 'humans_015':
      return require('audio/humans_015.mp3');
    case 'humans_016':
      return require('audio/humans_016.mp3');
    case 'humans_017':
      return require('audio/humans_017.mp3');
    case 'humans_018':
      return require('audio/humans_018.mp3');
    case 'humans_019':
      return require('audio/humans_019.mp3');
    case 'humans_020':
      return require('audio/humans_020.mp3');
    case 'humans_021':
      return require('audio/humans_021.mp3');
    case 'humans_022':
      return require('audio/humans_022.mp3');
    case 'humans_023':
      return require('audio/humans_023.mp3');
    case 'humans_024':
      return require('audio/humans_024.mp3');
    case 'humans_025':
      return require('audio/humans_025.mp3');
    case 'humans_026':
      return require('audio/humans_026.mp3');
    case 'humans_027':
      return require('audio/humans_027.mp3');
    case 'humans_028':
      return require('audio/humans_028.mp3');
    case 'humans_029':
      return require('audio/humans_029.mp3');
    case 'humans_030':
      return require('audio/humans_030.mp3');
    case 'humans_031':
      return require('audio/humans_031.mp3');
    case 'humans_032':
      return require('audio/humans_032.mp3');
    case 'humans_033':
      return require('audio/humans_033.mp3');
    case 'humans_034':
      return require('audio/humans_034.mp3');
    case 'humans_035':
      return require('audio/humans_035.mp3');
    case 'humans_036':
      return require('audio/humans_036.mp3');
    case 'humans_037':
      return require('audio/humans_037.mp3');
    case 'humans_038':
      return require('audio/humans_038.mp3');
    case 'humans_039':
      return require('audio/humans_039.mp3');
    case 'humans_040':
      return require('audio/humans_040.mp3');
    case 'humans_041':
      return require('audio/humans_041.mp3');
    case 'humans_042':
      return require('audio/humans_042.mp3');
    case 'humans_043':
      return require('audio/humans_043.mp3');
    case 'humans_044':
      return require('audio/humans_044.mp3');
    case 'humans_045':
      return require('audio/humans_045.mp3');
    case 'humans_046':
      return require('audio/humans_046.mp3');
    case 'humans_047':
      return require('audio/humans_047.mp3');
    case 'humans_048':
      return require('audio/humans_048.mp3');
    case 'humans_049':
      return require('audio/humans_049.mp3');
    case 'humans_050':
      return require('audio/humans_050.mp3');
    case 'humans_051':
      return require('audio/humans_051.mp3');
    case 'humans_052':
      return require('audio/humans_052.mp3');
    case 'humans_053':
      return require('audio/humans_053.mp3');
    case 'humans_054':
      return require('audio/humans_054.mp3');
    case 'humans_055':
      return require('audio/humans_055.mp3');
    case 'humans_056':
      return require('audio/humans_056.mp3');
    case 'humans_057':
      return require('audio/humans_057.mp3');
    case 'humans_058':
      return require('audio/humans_058.mp3');

    // Media
    case 'media_001':
      return require('audio/media_001.mp3');
    case 'media_002':
      return require('audio/media_002.mp3');
    case 'media_003':
      return require('audio/media_003.mp3');
    case 'media_004':
      return require('audio/media_004.mp3');
    case 'media_005':
      return require('audio/media_005.mp3');
    case 'media_006':
      return require('audio/media_006.mp3');
    case 'media_007':
      return require('audio/media_007.mp3');
    case 'media_008':
      return require('audio/media_008.mp3');
    case 'media_009':
      return require('audio/media_009.mp3');
    case 'media_010':
      return require('audio/media_010.mp3');
    case 'media_011':
      return require('audio/media_011.mp3');
    case 'media_012':
      return require('audio/media_012.mp3');
    case 'media_013':
      return require('audio/media_013.mp3');
    case 'media_014':
      return require('audio/media_014.mp3');
    case 'media_015':
      return require('audio/media_015.mp3');
    case 'media_016':
      return require('audio/media_016.mp3');
    case 'media_017':
      return require('audio/media_017.mp3');
    case 'media_018':
      return require('audio/media_018.mp3');
    case 'media_019':
      return require('audio/media_019.mp3');
    case 'media_020':
      return require('audio/media_020.mp3');
    case 'media_021':
      return require('audio/media_021.mp3');
    case 'media_022':
      return require('audio/media_022.mp3');
    case 'media_023':
      return require('audio/media_023.mp3');
    case 'media_024':
      return require('audio/media_024.mp3');
    case 'media_025':
      return require('audio/media_025.mp3');
    case 'media_026':
      return require('audio/media_026.mp3');
    case 'media_027':
      return require('audio/media_027.mp3');
    case 'media_028':
      return require('audio/media_028.mp3');
    case 'media_029':
      return require('audio/media_029.mp3');
    case 'media_030':
      return require('audio/media_030.mp3');
    case 'media_031':
      return require('audio/media_031.mp3');

    /// museums
    case 'museums_001':
      return require('audio/museums_001.mp3');
    case 'museums_002':
      return require('audio/museums_002.mp3');
    case 'museums_003':
      return require('audio/museums_003.mp3');
    case 'museums_004':
      return require('audio/museums_004.mp3');
    case 'museums_005':
      return require('audio/museums_005.mp3');
    case 'museums_006':
      return require('audio/museums_006.mp3');
    case 'museums_007':
      return require('audio/museums_007.mp3');
    case 'museums_008':
      return require('audio/museums_008.mp3');
    case 'museums_009':
      return require('audio/museums_009.mp3');
    case 'museums_010':
      return require('audio/museums_010.mp3');
    case 'museums_011':
      return require('audio/museums_011.mp3');
    case 'museums_012':
      return require('audio/museums_012.mp3');
    case 'museums_013':
      return require('audio/museums_013.mp3');
    case 'museums_014':
      return require('audio/museums_014.mp3');
    case 'museums_015':
      return require('audio/museums_015.mp3');
    case 'museums_016':
      return require('audio/museums_016.mp3');
    case 'museums_017':
      return require('audio/museums_017.mp3');
    case 'museums_018':
      return require('audio/museums_018.mp3');
    case 'museums_019':
      return require('audio/museums_019.mp3');

    case 'politics_001':
      return require('audio/politics_001.mp3');
    case 'politics_002':
      return require('audio/politics_002.mp3');
    case 'politics_003':
      return require('audio/politics_003.mp3');
    case 'politics_004':
      return require('audio/politics_004.mp3');
    case 'politics_005':
      return require('audio/politics_005.mp3');
    case 'politics_006':
      return require('audio/politics_006.mp3');
    case 'politics_007':
      return require('audio/politics_007.mp3');
    case 'politics_008':
      return require('audio/politics_008.mp3');
    case 'politics_009':
      return require('audio/politics_009.mp3');
    case 'politics_010':
      return require('audio/politics_010.mp3');
    case 'politics_011':
      return require('audio/politics_011.mp3');
    case 'politics_012':
      return require('audio/politics_012.mp3');
    case 'politics_013':
      return require('audio/politics_013.mp3');
    case 'politics_014':
      return require('audio/politics_014.mp3');
    case 'politics_015':
      return require('audio/politics_015.mp3');
    case 'politics_016':
      return require('audio/politics_016.mp3');
    case 'politics_017':
      return require('audio/politics_017.mp3');
    case 'politics_018':
      return require('audio/politics_018.mp3');
    case 'politics_019':
      return require('audio/politics_019.mp3');
    case 'politics_020':
      return require('audio/politics_020.mp3');
    case 'politics_021':
      return require('audio/politics_021.mp3');
    case 'politics_022':
      return require('audio/politics_022.mp3');
    case 'politics_023':
      return require('audio/politics_023.mp3');
    case 'politics_024':
      return require('audio/politics_024.mp3');
    case 'politics_025':
      return require('audio/politics_025.mp3');
    case 'politics_026':
      return require('audio/politics_026.mp3');
    case 'politics_027':
      return require('audio/politics_027.mp3');
    case 'politics_028':
      return require('audio/politics_028.mp3');
    case 'politics_029':
      return require('audio/politics_029.mp3');
    case 'politics_030':
      return require('audio/politics_030.mp3');
    case 'politics_031':
      return require('audio/politics_031.mp3');
    case 'politics_032':
      return require('audio/politics_032.mp3');
    case 'politics_033':
      return require('audio/politics_033.mp3');
    case 'politics_034':
      return require('audio/politics_034.mp3');
    case 'politics_035':
      return require('audio/politics_035.mp3');
    case 'politics_036':
      return require('audio/politics_036.mp3');
    case 'politics_037':
      return require('audio/politics_037.mp3');

    ///purchases
    case 'purchases_001':
      return require('audio/purchases_001.mp3');
    case 'purchases_002':
      return require('audio/purchases_002.mp3');
    case 'purchases_003':
      return require('audio/purchases_003.mp3');
    case 'purchases_004':
      return require('audio/purchases_004.mp3');
    case 'purchases_005':
      return require('audio/purchases_005.mp3');
    case 'purchases_006':
      return require('audio/purchases_006.mp3');
    case 'purchases_007':
      return require('audio/purchases_007.mp3');
    case 'purchases_008':
      return require('audio/purchases_008.mp3');
    case 'purchases_009':
      return require('audio/purchases_009.mp3');
    case 'purchases_010':
      return require('audio/purchases_010.mp3');
    case 'purchases_011':
      return require('audio/purchases_011.mp3');
    case 'purchases_012':
      return require('audio/purchases_012.mp3');
    case 'purchases_013':
      return require('audio/purchases_013.mp3');
    case 'purchases_014':
      return require('audio/purchases_014.mp3');
    case 'purchases_015':
      return require('audio/purchases_015.mp3');
    case 'purchases_016':
      return require('audio/purchases_016.mp3');
    case 'purchases_017':
      return require('audio/purchases_017.mp3');
    case 'purchases_018':
      return require('audio/purchases_018.mp3');
    case 'purchases_019':
      return require('audio/purchases_019.mp3');
    case 'purchases_020':
      return require('audio/purchases_020.mp3');
    case 'purchases_021':
      return require('audio/purchases_021.mp3');
    case 'purchases_022':
      return require('audio/purchases_022.mp3');
    case 'purchases_023':
      return require('audio/purchases_023.mp3');
    case 'purchases_024':
      return require('audio/purchases_024.mp3');
    case 'purchases_025':
      return require('audio/purchases_025.mp3');
    case 'purchases_026':
      return require('audio/purchases_026.mp3');
    case 'purchases_027':
      return require('audio/purchases_027.mp3');
    case 'purchases_028':
      return require('audio/purchases_028.mp3');
    case 'purchases_029':
      return require('audio/purchases_029.mp3');
    case 'purchases_030':
      return require('audio/purchases_030.mp3');
    case 'purchases_031':
      return require('audio/purchases_031.mp3');
    case 'purchases_032':
      return require('audio/purchases_032.mp3');
    case 'purchases_033':
      return require('audio/purchases_033.mp3');
    case 'purchases_034':
      return require('audio/purchases_034.mp3');
    case 'purchases_035':
      return require('audio/purchases_035.mp3');
    case 'purchases_036':
      return require('audio/purchases_036.mp3');
    case 'purchases_037':
      return require('audio/purchases_037.mp3');

    /// time
    case 'time_001':
      return require('audio/time_001.mp3');
    case 'time_002':
      return require('audio/time_002.mp3');
    case 'time_003':
      return require('audio/time_003.mp3');
    case 'time_004':
      return require('audio/time_004.mp3');
    case 'time_005':
      return require('audio/time_005.mp3');
    case 'time_006':
      return require('audio/time_006.mp3');
    case 'time_007':
      return require('audio/time_007.mp3');
    case 'time_008':
      return require('audio/time_008.mp3');
    case 'time_009':
      return require('audio/time_009.mp3');
    case 'time_010':
      return require('audio/time_010.mp3');
    case 'time_011':
      return require('audio/time_011.mp3');
    case 'time_012':
      return require('audio/time_012.mp3');
    case 'time_013':
      return require('audio/time_013.mp3');
    case 'time_014':
      return require('audio/time_014.mp3');
    case 'time_015':
      return require('audio/time_015.mp3');
    case 'time_016':
      return require('audio/time_016.mp3');
    case 'time_017':
      return require('audio/time_017.mp3');
    case 'time_018':
      return require('audio/time_018.mp3');
    case 'time_019':
      return require('audio/time_019.mp3');
    case 'time_020':
      return require('audio/time_020.mp3');
    case 'time_021':
      return require('audio/time_021.mp3');
    case 'time_022':
      return require('audio/time_022.mp3');
    case 'time_023':
      return require('audio/time_023.mp3');
    case 'time_024':
      return require('audio/time_024.mp3');
    case 'time_025':
      return require('audio/time_025.mp3');
    case 'time_026':
      return require('audio/time_026.mp3');
    case 'time_027':
      return require('audio/time_027.mp3');
    case 'time_028':
      return require('audio/time_028.mp3');
    case 'time_029':
      return require('audio/time_029.mp3');
    case 'time_030':
      return require('audio/time_030.mp3');
    case 'time_031':
      return require('audio/time_031.mp3');
    case 'time_032':
      return require('audio/time_032.mp3');
    case 'time_033':
      return require('audio/time_033.mp3');
    case 'time_034':
      return require('audio/time_034.mp3');
    case 'time_035':
      return require('audio/time_035.mp3');
    case 'time_036':
      return require('audio/time_036.mp3');
    case 'time_037':
      return require('audio/time_037.mp3');
    case 'time_038':
      return require('audio/time_038.mp3');
    case 'time_039':
      return require('audio/time_039.mp3');
    case 'time_040':
      return require('audio/time_040.mp3');
    case 'time_041':
      return require('audio/time_041.mp3');
    case 'time_042':
      return require('audio/time_042.mp3');
    case 'time_043':
      return require('audio/time_043.mp3');
    case 'time_044':
      return require('audio/time_044.mp3');
    case 'time_045':
      return require('audio/time_045.mp3');
    case 'time_046':
      return require('audio/time_046.mp3');
    case 'time_047':
      return require('audio/time_047.mp3');
    case 'time_048':
      return require('audio/time_048.mp3');
    case 'time_049':
      return require('audio/time_049.mp3');
    case 'time_050':
      return require('audio/time_050.mp3');
    case 'time_051':
      return require('audio/time_051.mp3');

    /// transportation
    case 'transportation_001':
      return require('audio/transportation_001.mp3');
    case 'transportation_002':
      return require('audio/transportation_002.mp3');
    case 'transportation_003':
      return require('audio/transportation_003.mp3');
    case 'transportation_004':
      return require('audio/transportation_004.mp3');
    case 'transportation_005':
      return require('audio/transportation_005.mp3');
    case 'transportation_006':
      return require('audio/transportation_006.mp3');
    case 'transportation_007':
      return require('audio/transportation_007.mp3');
    case 'transportation_008':
      return require('audio/transportation_008.mp3');
    case 'transportation_009':
      return require('audio/transportation_009.mp3');
    case 'transportation_010':
      return require('audio/transportation_010.mp3');
    case 'transportation_011':
      return require('audio/transportation_011.mp3');
    case 'transportation_012':
      return require('audio/transportation_012.mp3');
    case 'transportation_013':
      return require('audio/transportation_013.mp3');
    case 'transportation_014':
      return require('audio/transportation_014.mp3');
    case 'transportation_015':
      return require('audio/transportation_015.mp3');
    case 'transportation_016':
      return require('audio/transportation_016.mp3');
    case 'transportation_017':
      return require('audio/transportation_017.mp3');
    case 'transportation_018':
      return require('audio/transportation_018.mp3');
    case 'transportation_019':
      return require('audio/transportation_019.mp3');
    case 'transportation_020':
      return require('audio/transportation_020.mp3');
    case 'transportation_021':
      return require('audio/transportation_021.mp3');
    case 'transportation_022':
      return require('audio/transportation_022.mp3');
    case 'transportation_023':
      return require('audio/transportation_023.mp3');
    case 'transportation_024':
      return require('audio/transportation_024.mp3');
    case 'transportation_025':
      return require('audio/transportation_025.mp3');
    case 'transportation_026':
      return require('audio/transportation_026.mp3');
    case 'transportation_027':
      return require('audio/transportation_027.mp3');
    case 'transportation_028':
      return require('audio/transportation_028.mp3');
    case 'transportation_029':
      return require('audio/transportation_029.mp3');
    case 'transportation_030':
      return require('audio/transportation_030.mp3');
    case 'transportation_031':
      return require('audio/transportation_031.mp3');
    case 'transportation_032':
      return require('audio/transportation_032.mp3');
    case 'transportation_033':
      return require('audio/transportation_033.mp3');
    case 'transportation_034':
      return require('audio/transportation_034.mp3');
    case 'transportation_035':
      return require('audio/transportation_035.mp3');
    case 'transportation_036':
      return require('audio/transportation_036.mp3');
    case 'transportation_037':
      return require('audio/transportation_037.mp3');
    case 'transportation_038':
      return require('audio/transportation_038.mp3');
    case 'transportation_039':
      return require('audio/transportation_039.mp3');
    case 'transportation_040':
      return require('audio/transportation_040.mp3');
    case 'transportation_041':
      return require('audio/transportation_041.mp3');
    case 'transportation_042':
      return require('audio/transportation_042.mp3');
  }
};
